#!/bin/sh
set -eu

: "${POSTGRES_HOST:?POSTGRES_HOST is required}"
: "${POSTGRES_PORT:?POSTGRES_PORT is required}"
: "${POSTGRES_DB_NAME:?POSTGRES_DB_NAME is required}"
: "${DB_APP_READ_USERNAME:?DB_APP_READ_USERNAME is required}"
: "${DB_APP_WRITE_USERNAME:?DB_APP_WRITE_USERNAME is required}"
: "${DB_APP_ADMIN_USERNAME:?DB_APP_ADMIN_USERNAME is required}"
: "${DB_APP_ADMIN_PASSWORD:?DB_APP_ADMIN_PASSWORD is required}"

export PGPASSWORD="$DB_APP_ADMIN_PASSWORD"

psql \
  --host "$POSTGRES_HOST" \
  --port "$POSTGRES_PORT" \
  --username "$DB_APP_ADMIN_USERNAME" \
  --dbname "$POSTGRES_DB_NAME" \
  --set read_user="$DB_APP_READ_USERNAME" \
  --set write_user="$DB_APP_WRITE_USERNAME" \
  --set admin_user="$DB_APP_ADMIN_USERNAME" \
  -v ON_ERROR_STOP=1 <<'SQL'
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public, system, analytics, audit FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA public, system, analytics, audit FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public, system, analytics, audit FROM PUBLIC;

GRANT USAGE ON SCHEMA public, system, analytics, audit TO :"read_user";
GRANT USAGE ON SCHEMA public, system, analytics, audit TO :"write_user";
GRANT ALL ON SCHEMA public, system, analytics, audit TO :"admin_user";

GRANT SELECT ON ALL TABLES IN SCHEMA public, system, analytics, audit TO :"read_user";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public, system, analytics, audit TO :"write_user";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public, system, analytics, audit TO :"write_user";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public, system, analytics, audit TO :"admin_user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public, system, analytics, audit TO :"admin_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA public
  GRANT SELECT ON TABLES TO :"read_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA system
  GRANT SELECT ON TABLES TO :"read_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA analytics
  GRANT SELECT ON TABLES TO :"read_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA audit
  GRANT SELECT ON TABLES TO :"read_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"write_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA system
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"write_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA analytics
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"write_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA audit
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"write_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO :"write_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA system
  GRANT USAGE, SELECT ON SEQUENCES TO :"write_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA analytics
  GRANT USAGE, SELECT ON SEQUENCES TO :"write_user";
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA audit
  GRANT USAGE, SELECT ON SEQUENCES TO :"write_user";

ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA public
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA system
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA analytics
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA audit
  REVOKE ALL ON TABLES FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA system
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA analytics
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE :"admin_user" IN SCHEMA audit
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
SQL
